# This workflow will build a Docker image

name: Docker CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"

env:
  REPO: ${{ github.event.repository.name }}
  OWNER: ${{ github.event.repository.owner.login }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  HEAD_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}

jobs:
  build-template:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install bower
        run: npm install -g markdown-toc@latest secretlint@latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push debug
        run: echo "docker push ${{ env.OWNER }}/${{ github.event.repository.name }}:latest,${{ github.repository }}:${{ github.sha }}"

      - name: Print the GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          #tags: ${{ github.repository }}:latest,${{ github.repository }}:${{ github.sha }}
          tags: ${{ github.repository }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.repository }}:latest
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          # format: 'table'
          # exit-code: '1'
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
